app:
    companyName: 淘劵猪
    dynamicResLocation: file:F:/tjz/fileStorage/
spring:
    h2.console:
        enabled: true
        settings.web-allow-others: true
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:tcp://localhost:9092/F:/tjz/tjz;MODE=MYSQL
        #url: jdbc:h2:mem:akkb;MODE=MYSQL
        username: test
        password: test
        initialize: false
    jpa:
        properties:
            hibernate:
                #update none
                hbm2ddl.auto: update
                show_sql: true
                format_sql: true
    devtools.restart.enabled: false
    mvc:
        static-path-pattern: /static/public/**
    resources:
        static-locations: classpath:/static/
    freemarker:
        expose-request-attributes: true
        expose-session-attributes: true
        expose-spring-macro-helpers: true
        request-context-attribute: request
        settings:
            classic_compatible: true
            template_exception_handler: ignore
            object_wrapper: com.abc.tjz.util.ftl.CustomObjectWrapper
            number_format: '#.##'
            datetime_format: yyyy-MM-dd HH:mm:ss
            date_format: yyyy-MM-dd
            time_format: HH:mm:ss
server:
    port: 80
    context-path: /tjz
security:
    basic:
        enabled: true
        realm: ${server.context-path}
        path: /action/adm/**
    user:
        name: adm
        password: 123456




