CREATE TABLE T_CATEGORY(
    ID VARCHAR(36) NOT NULL,
    CREATE_DATETIME TIMESTAMP,
    UPDATE_DATETIME TIMESTAMP,
    NAME VARCHAR(50),
    SEQ INTEGER DEFAULT 0,
    PARENT_ID VARCHAR(36)
);
ALTER TABLE T_CATEGORY ADD CONSTRAINT CONSTRAINT_5 PRIMARY KEY(ID);             
CREATE TABLE T_CATEGORY_REL(
    REL_ID VARCHAR(36) NOT NULL,
    CATEGORY_ID VARCHAR(36) NOT NULL
);        
ALTER TABLE T_CATEGORY_REL ADD CONSTRAINT CONSTRAINT_4 PRIMARY KEY(REL_ID, CATEGORY_ID);        
CREATE TABLE T_COUPON_CX(
    ID VARCHAR(36) NOT NULL,
    CREATE_DATETIME TIMESTAMP,
    UPDATE_DATETIME TIMESTAMP,
    COUPON_NAME VARCHAR(500),
    DETAIL_IMAGE_PATH VARCHAR(1000),
    IS_DELETED BOOLEAN DEFAULT FALSE,
    LINK VARCHAR(1000),
    PAGEVIEWS INTEGER DEFAULT 0,
    RULES TEXT,
    START_TIME VARCHAR(20),
    SUMMARY TEXT,
    THUMB_IMAGE_PATH VARCHAR(1000),
    TIP VARCHAR(500),
    CATEGORY_ID VARCHAR(36)
);            
ALTER TABLE T_COUPON_CX ADD CONSTRAINT CONSTRAINT_7 PRIMARY KEY(ID);            
CREATE TABLE T_COUPON_KC(
    ID VARCHAR(36) NOT NULL,
    CREATE_DATETIME TIMESTAMP,
    UPDATE_DATETIME TIMESTAMP,
    COUPON_NAME VARCHAR(500),
    COUPON_PRICE INTEGER,
    DETAIL_IMAGE_PATH VARCHAR(1000),
    EXPIRE_TIME VARCHAR(20),
    IS_DELETED BOOLEAN DEFAULT FALSE,
    THUMB_IMAGE_PATH VARCHAR(1000),
    CATEGORY_ID VARCHAR(36)
);      
ALTER TABLE T_COUPON_KC ADD CONSTRAINT CONSTRAINT_7C PRIMARY KEY(ID);           
CREATE TABLE T_COUPON_TB(
    ID VARCHAR(36) NOT NULL,
    CREATE_DATETIME TIMESTAMP,
    UPDATE_DATETIME TIMESTAMP,
    BUY_PRICE INTEGER ,
    BUYER_COUNT INTEGER DEFAULT 0 ,
    COUPON_PRICE INTEGER ,
    GOODS_NAME VARCHAR(1000) ,
    IMAGE_PATH VARCHAR(1000) ,
    IS_DELETED BOOLEAN DEFAULT FALSE ,
    LINK VARCHAR(1000),
    OLD_PRICE INTEGER ,
    CATEGORY_ID VARCHAR(36) 
);               
ALTER TABLE T_COUPON_TB ADD CONSTRAINT CONSTRAINT_7C2 PRIMARY KEY(ID);          
CREATE TABLE T_COUPON_WM(
    ID VARCHAR(36) NOT NULL,
    CREATE_DATETIME TIMESTAMP,
    UPDATE_DATETIME TIMESTAMP,
    COUPON_NAME VARCHAR(500),
    DETAIL_IMAGE_PATH VARCHAR(1000),
    IS_DELETED BOOLEAN DEFAULT FALSE,
    LINK VARCHAR(1000),
    PAGEVIEWS INTEGER DEFAULT 0,
    RULES TEXT,
    START_TIME VARCHAR(20),
    SUMMARY TEXT,
    THUMB_IMAGE_PATH VARCHAR(1000),
    TIP VARCHAR(500),
    CATEGORY_ID VARCHAR(36)
);            
ALTER TABLE T_COUPON_WM ADD CONSTRAINT CONSTRAINT_7C25 PRIMARY KEY(ID);         
CREATE TABLE T_TEST(
    ID VARCHAR(36) NOT NULL,
    CREATE_DATETIME TIMESTAMP,
    UPDATE_DATETIME TIMESTAMP,
    NAME VARCHAR(255)
);           
ALTER TABLE T_TEST ADD CONSTRAINT CONSTRAINT_9 PRIMARY KEY(ID); 
